### ISSUE TITLE
Improve validation error quality

### ISSUE THREAD

**Issue by sayanarijit** [rapidstack/RESTEasyCLI#33]
Invalid file: **sites.yml**

```yaml
version: v0.1
sites:
  ghjobs:
    base_url: https://jobs.github.com
    endpoint_urls:     # <- here is the error
      p:
        route: positions.json
        timeout: 10
        methods: [ GET ]
```

Error shown:

```bash
(RESTEasyCLI) ➜  RESTEasyCLI git:(master) recli list-sites
error: ./sites.yml: sites: !!python/object/apply:collections.defaultdict
  args:
  - !!python/name:builtins.dict ''
  dictitems:
    ghjobs:
      value:
        endpoint_urls:
        - Unknown field.
        endpoints:
        - Missing data for required field.
```

^ This should look like:

```bash
(RESTEasyCLI) ➜  RESTEasyCLI git:(master) recli list-sites
error: ./sites.yml: while reading this file below errors were found:
ghjobs:
  endpoint_urls: Unknown field.
  endpoints: Missing data for required field.
```

Hint: Here is the error formatting logic: https://github.com/rapidstack/RESTEasyCLI/blob/a30b62fd963ec364657cc4b8d851c8a68384c070/resteasycli/lib/workspace.py#L166 

There may be a need of using recursive algorithm to format the string. error list can be joined using `, ` (comma followed by space)
